---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ofeerist.
--- DateTime: 18.02.2023 19:45
---
currentLevel = 0
database = {
    {
        gridSize = 2,
        gold = 500,
        wood = 300,
        bandits = {
            {
                { id = 'ncfs', min = 1, max = 2 },
            },
            {
                { id = 'nsca', min = 1, max = 3 },
            },
            {
                { id = 'nglm', min = 1, max = 3 },
            },
            {
                { id = 'ndrl', min = 1, max = 2 },
            },
            {
                { id = 'npng', min = 1, max = 1 },
            },
            {
                { id = 'ndog', min = 1, max = 1 },
            },
            {
                { id = 'nrat', min = 5, max = 10 },
            },
        },
        altar = {
            {
                { id = 'ndrj', min = 1, max = 1 },
            },
            {
                { id = 'nsca', min = 1, max = 1 },
            },
            {
                { id = 'ndrl', min = 1, max = 1 },
            }
        }
    },
    {
        gridSize = 3,
        gold = 800,
        wood = 500,
        bandits = {
            {
                { id = 'ncfs', min = 2, max = 4 },
            },
            {
                { id = 'nsca', min = 3, max = 5 },
            },
            {
                { id = 'nglm', min = 2, max = 4 },
            },
            {
                { id = 'ndrl', min = 2, max = 3 },
            }
        },
        altar = {
            {
                { id = 'ndrj', min = 1, max = 2 },
            },
            {
                { id = 'nsca', min = 1, max = 2 },
            },
            {
                { id = 'ndrl', min = 1, max = 2 },
            }
        }
    },
    {
        gridSize = 3,
        gold = 1000,
        wood = 700,
        bandits = {
            {
                { id = 'ncfs', min = 2, max = 4 },
            },
            {
                { id = 'nsca', min = 3, max = 5 },
            },
            {
                { id = 'nglm', min = 2, max = 4 },
            },
            {
                { id = 'ndrl', min = 2, max = 3 },
            }
        },
        altar = {
            {
                { id = 'ndrj', min = 2, max = 5 },
            },
            {
                { id = 'nsca', min = 2, max = 5 },
            },
            {
                { id = 'ndrl', min = 2, max = 5 },
            }
        }
    },
    {
        gridSize = 4,
        gold = 2000,
        wood = 1500,
        bandits = {
            {
                { id = 'ncfs', min = 2, max = 4 },
            },
            {
                { id = 'nsca', min = 3, max = 5 },
            },
            {
                { id = 'nglm', min = 2, max = 4 },
            },
            {
                { id = 'ndrl', min = 2, max = 3 },
            }
        },
        altar = {
            {
                { id = 'ninf', min = 1, max = 1 },
            },
            {
                { id = 'nbal', min = 1, max = 1 },
            },
            {
                { id = 'nskf', min = 1, max = 3 },
            }
        }
    },
    {
        gridSize = 5,
        gold = 3000,
        wood = 1500,
        bandits = {
            {
                { id = 'nrog', min = 2, max = 8 },
                { id = 'nass', min = 0, max = 6 },
                { id = 'nenf', min = 0, max = 5 },
                { id = 'nbld', min = 1, max = 3 },
            },
            {
                { id = 'nanw', min = 1, max = 5 },
                { id = 'nanm', min = 0, max = 4 },
                { id = 'nano', min = 1, max = 6 },
            },
            {
                { id = 'ncer', min = 1, max = 5 },
                { id = 'ncea', min = 0, max = 4 },
                { id = 'ncks', min = 1, max = 5 },
            },
            {
                { id = 'ndrf', min = 2, max = 3 },
                { id = 'ndrw', min = 0, max = 6 },
                { id = 'ndrd', min = 0, max = 4 },
            }
        },
        altar = {
            {
                { id = 'ncer', min = 1, max = 5 },
                { id = 'ncea', min = 0, max = 4 },
                { id = 'ncks', min = 1, max = 5 },
            },
            {
                { id = 'ndrf', min = 2, max = 3 },
                { id = 'ndrw', min = 0, max = 6 },
                { id = 'ndrd', min = 0, max = 4 },
            },
            {
                { id = 'nskf', min = 3, max = 5 },
            }
        }
    },
    {
        gridSize = 6,
        gold = 5000,
        wood = 5000,
        bandits = {
            {
                { id = 'nrog', min = 2, max = 8 },
                { id = 'nass', min = 0, max = 7 },
                { id = 'nenf', min = 0, max = 7 },
                { id = 'nbld', min = 3, max = 3 },
            },
            {
                { id = 'nanw', min = 1, max = 9 },
                { id = 'nanm', min = 0, max = 9 },
                { id = 'nano', min = 1, max = 5 },
            },
            {
                { id = 'ncer', min = 1, max = 9 },
                { id = 'ncea', min = 0, max = 9 },
                { id = 'ncks', min = 1, max = 5 },
            },
            {
                { id = 'ndrf', min = 2, max = 9 },
                { id = 'ndrw', min = 0, max = 5 },
                { id = 'ndrd', min = 0, max = 5 },
            }
        },
        altar = {
            {
                { id = 'ncer', min = 1, max = 9 },
                { id = 'ncea', min = 0, max = 9 },
                { id = 'ncks', min = 1, max = 5 },
            },
            {
                { id = 'nrog', min = 2, max = 8 },
                { id = 'nass', min = 0, max = 7 },
                { id = 'nenf', min = 0, max = 7 },
                { id = 'nbld', min = 3, max = 3 },
            },
            {
                { id = 'nskf', min = 3, max = 5 },
            }
        }
    }
}