---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ofeerist.
--- DateTime: 19.02.2023 1:16
---

dropDatabase = {
    {
        id = 'B001',
        drops = {
            {
                drop='belv'
            },
            {
                drop='ratc'
            },
            {
                drop='rde3'
            },
            {
                drop='rwiz'
            },
            {
                drop='gcel'
            },
            {
                drop='bgst'
            },
            {
                drop='hval'
            },
            {
                drop='odef'
            },
            {
                drop='ward'
            },
            {
                drop='penr'
            },
            {
                drop='pmna'
            },
            {
                drop='rag1'
            },
            {
                drop='wild'
            },
            {
                drop='ankh'
            },
            {
                drop='pnvu'
            },
            {
                drop='hlst'
            },
            {
                drop='shar'
            },
            {
                drop='fgdg'
            },
            {
                drop='totw'
            },
            {
                drop='fgfh'
            },
            {
                drop='rej3'
            },
            {
                drop='ratf'
            },
            {
                drop='modt'
            },
            {
                drop='ckng'
            }
        },
    },
    {
        id = 'B007',
        drops = {
            {
                drop='shhn'
            },
            {
                drop='engr'
            },
            {
                drop='sksh'
            },
            {
                drop='shdt'
            },
            {
                drop='rugt'
            },
            {
                drop='ckng'
            },
            {
                drop='rag1'
            },
            {
                drop='hval'
            },
            {
                drop='rde3'
            },
            {
                drop='rde2'
            },
            {
                drop='rwiz'
            },
            {
                drop='brac'
            },
        }
    },
    {
        id = 'B006',
        drops = {
            {
                drop = 'ratc'
            },
            {
                drop = 'rat6'
            },
            {
                drop = 'rat9'
            },
            {
                drop = 'rst1'
            },
            {
                drop = 'gcel'
            },
            {
                drop = 'afac'
            },
            {
                drop = 'ratf'
            },
            {
                drop = 'desc'
            },
            {
                drop = 'frgd'
            },
            {
                drop = 'srbd'
            },
            {
                drop = 'rump'
            },
            {
                drop = 'ccmd'
            },
            {
                drop = 'schl'
            },
            {
                drop = 'rots'
            },

        }
    },
    {
        id = 'B000',
        drops = {
            {
                drop='wneu'
            },
            {
                drop='wneg'
            },
            {
                drop='pclr'
            },
            {
                drop='pinv'
            },
            {
                drop='hslv'
            },
            {
                drop='stwp'
            },
            {
                drop='sreg'
            },
            {
                drop='shas'
            },
            {
                drop='tret'
            },
            {
                drop='pnvl'
            },
            {
                drop='plcl'
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },{
                drop=''
            },{
                drop=''
            },{
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },{
                drop=''
            },{
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },
        }
    },
    {
        id = 'B004',
        drops = {
            {
                drop='wneu'
            },
            {
                drop='wneg'
            },
            {
                drop='pclr'
            },
            {
                drop='pinv'
            },
            {
                drop='hslv'
            },
            {
                drop='stwp'
            },
            {
                drop='sreg'
            },
            {
                drop='shas'
            },
            {
                drop='tret'
            },
            {
                drop='pnvl'
            },
            {
                drop='plcl'
            }
        }
    },
    {
        id = 'B008',
        drops = {
            {
                drop='wneu'
            },
            {
                drop='wneg'
            },
            {
                drop='pclr'
            },
            {
                drop='pinv'
            },
            {
                drop='hslv'
            },
            {
                drop='stwp'
            },
            {
                drop='sreg'
            },
            {
                drop='shas'
            },
            {
                drop='tret'
            },
            {
                drop='pnvl'
            },
            {
                drop='plcl'
            }
        }
    },
    {
        id = 'B009',
        drops = {
            {
                drop='wneu'
            },
            {
                drop='wneg'
            },
            {
                drop='pclr'
            },
            {
                drop='pinv'
            },
            {
                drop='hslv'
            },
            {
                drop='stwp'
            },
            {
                drop='sreg'
            },
            {
                drop='shas'
            },
            {
                drop='tret'
            },
            {
                drop='pnvl'
            },
            {
                drop='plcl'
            }
        }
    },
    {
        id = 'LTcr',
        drops = {
            {
                drop='lmbr'
            },
            {
                drop='lmbr'
            },
            {
                drop='lmbr'
            },
            {
                drop='lmbr'
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            }
        }
    },
    {
        id = 'B003',
        drops = {
            {
                drop='gold'
            },
            {
                drop='gold'
            },
            {
                drop='gold'
            },
            {
                drop='gold'
            },
            {
                drop='gold'
            },
            {
                drop='gold'
            },
            {
                drop='gold'
            },
            {
                drop='gold'
            },
            {
                drop=''
            },
            {
                drop=''
            },
            {
                drop=''
            }
        }
    },
}

itemsCreated = {}
dropTrigger = nil
function DropOnKillStart()
    if (not dropTrigger == nil) then
        DropOnKillDestroy()
    end

    dropTrigger = CreateTrigger()
    TriggerAddAction(dropTrigger, OnDeathDrop)
end

function DropOnKillDestroy()
    DestroyTrigger(dropTrigger)
    dropTrigger = nil
end

function OnDeathDrop()

    local dest = GetTriggerDestructable()

    for i = 1, #dropDatabase do
        local key = dropDatabase[i]

        if (GetDestructableTypeId(dest) == FourCC(key.id)) then
            local drop = dropDatabase[i].drops[GetRandomInt(1, #dropDatabase[i].drops)].drop

            if (drop == '') then

            else
                item = CreateItem(FourCC(drop), GetDestructableX(dest), GetDestructableY(dest))
                table.insert(itemsCreated, item)
            end
        end

    end
end