---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ofeerist.
--- DateTime: 19.02.2023 16:14
---
textFrame = nil
helpText = nil
timerTime = 15 * 60
timerTimer = nil
function DungeonTimerStart()
    helpText = BlzCreateFrameByType("TEXT", "ButtonChargesText", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    BlzFrameSetAbsPoint(helpText, FRAMEPOINT_CENTER, 0.4, 0.17)
    BlzFrameSetText(helpText, "У вас еще есть время успеть выйти из подземелья!")
    BlzFrameSetScale(helpText, 1.6)

    textFrame = BlzCreateFrameByType("TEXT", "ButtonChargesText", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    BlzFrameSetAbsPoint(textFrame, FRAMEPOINT_CENTER, 0.4, 0.2)
    BlzFrameSetText(textFrame, "")
    BlzFrameSetScale(textFrame, 2)

    timerTimer = CreateTimer()
    TimerStart(timerTimer, 1, true, function()
        timerTime = timerTime - 1
        BlzFrameSetText(textFrame, DecimalsToMinutes(timerTime))

        if (timerTime < 5 * 60) then
            PlaySound("Sound/Interface/MouseClick1.flac")
        elseif (timerTime < 10 * 60) then
            PlaySound("Sound/Interface/MouseClick2.flac")
        end

        if (timerTime <= 0) then
            for i = 0, 10 do
                RemovePlayerPreserveUnitsBJ(Player(i), PLAYER_GAME_RESULT_DEFEAT, false)
            end

            BlzFrameSetText(helpText, "У вас больше нет времени ((((")
            DestroyTimer(timerTimer)

            PlaySound("Sound/Music/mp3Music/HumanDefeat.flac")
        end
    end)
end

function WinTimer()
    for i = 0, 10 do
        RemovePlayerPreserveUnitsBJ(Player(i), PLAYER_GAME_RESULT_VICTORY, false)
    end

    BlzFrameSetText(helpText, "Вы успели!")
    DestroyTimer(timerTimer)

    PlaySound("Sound/Music/mp3Music/Credits.flac")
end

function DecimalsToMinutes(dec)
    local ms = tonumber(dec)
    return Zero(math.floor(ms / 60))..":"..Zero((ms % 60))
end

function Zero(s)
    local ns = ""
    if string.len(s) == 1 then
        ns = "0" .. s
    else
        ns = s
    end
    return ns
end