---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ofeerist.
--- DateTime: 18.02.2023 23:42
---
---
evolution = {
    {id = 'hfoo', text = "Пехотинец", require = "1"},
    {id = 'nban', text = "Бандит", require = "1"},
    {id = 'hcth', text = "Капитан", require = "11"},
    {id = 'hhes', text = "Мечник", require = "11"},
    {id = 'nbrg', text = "Грабитель", require = "12"},
    {id = 'nrog', text = "Разбойник", require = "12"},
    {id = 'hrif', text = "Стрелок", require = "111"},
    {id = 'njks', text = "Тюремщик", require = "111"},
    {id = 'hkni', text = "Рыцарь", require = "112"},
    {id = 'nwzr', text = "Непокорный маг", require = "112"},
    {id = 'nenf', text = "Головорез", require = "121"},
    {id = 'nwzw', text = "Чародей крови", require = "121"},
    {id = 'nass', text = "Убийца", require = "122"},
    {id = 'nwzw', text = "Чародей крови", require = "122"},
    {id = 'Hmkg', text = "Горный король", require = "1111"},
    {id = 'Hamg', text = "Верховный маг", require = "1112"},
    {id = 'Hlgr', text = "Гаритос", require = "1121"},
    {id = 'Hblm', text = "Маг крови", require = "1122"},
    {id = 'Nbrn', text = "Темный следопыт", require = "1211"},
    {id = 'Hblm', text = "Маг крови", require = "1212"},
    {id = 'Nbrn', text = "Темный следопыт", require = "1221"},
    {id = 'Hblm', text = "Маг крови", require = "1222"},
}
function NextEvolution(player)

    CreateEvolutionDialog(player, currentLevel)

end

currentEvolution = {}

function CreateNextUnit(player, rawcode)
    local id = GetPlayerId(player)
    local unit = playerUnits[id]
    local newUnit = nil

    if (playerUnits[id] == nil) then return end

    RemoveUnit(unit)

    newUnit = CreateUnit(player, FourCC(rawcode), GetUnitX(unit), GetUnitY(unit), GetUnitFacing(unit))
    SelectUnitForPlayerSingle(newUnit, player)
    UnitAddAbility(newUnit, FourCC('AInv'))
    UnitAddAbility(newUnit, FourCC('Asal'))

    if (IsHeroUnitId(FourCC(rawcode))) then
        AddHeroXP(newUnit, 99999, true)
    end

    UnitAddItem(newUnit, UnitItemInSlot(unit, 0))
    UnitAddItem(newUnit, UnitItemInSlot(unit, 1))
    UnitAddItem(newUnit, UnitItemInSlot(unit, 2))
    UnitAddItem(newUnit, UnitItemInSlot(unit, 3))
    UnitAddItem(newUnit, UnitItemInSlot(unit, 4))
    UnitAddItem(newUnit, UnitItemInSlot(unit, 5))

    playerUnits[id] = newUnit
end

function CreateEvolutionDialog(player, level)
    local id = GetPlayerId(player)

    local dialog = DialogCreate()

    local buttonCount = 0
    for i = 1, #evolution do
        if (evolution[i].require == playerChooses[id]) then
            buttonCount = buttonCount + 1

            local button = DialogAddButton(dialog, evolution[i].text, 0)
            local trigger = CreateTrigger()
            TriggerRegisterDialogButtonEvent(trigger, button)
            local count = buttonCount
            TriggerAddAction(trigger, function()

                playerChooses[id] = playerChooses[id] .. tostring(count)

                currentEvolution[id] = evolution[i].id
                CreateNextUnit(player, evolution[i].id)

                DestroyTrigger(trigger)
                DialogClear(dialog)
            end)
        end
    end

    if (buttonCount > 0) then
        DialogDisplay(player, dialog, true)
    end
end