---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ofeerist.
--- DateTime: 18.02.2023 21:31
---
---

exitTrigger = nil

function CreateExit(center)
    CreateFiller( 'OTsp', center.x,  center.y, 45, 1, 1)

    if (not exitTrigger == nil) then
        DestroyTrigger(exitTrigger)
        exitTrigger = nil
    end

    exitTrigger = CreateTrigger()
    TriggerRegisterEnterRectSimple(exitTrigger, Rect(center.x - semiGridScale - semiWidth, center.y - semiGridScale - semiWidth,
            center.x + semiGridScale - semiWidth, center.y + semiGridScale - semiWidth))
    TriggerAddAction(exitTrigger, ShowEndDialog)

    table.insert(triggersCreated, exitTrigger)
end