---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ofeerist.
--- DateTime: 18.02.2023 22:51
---

function LobbyStart()

    gameLobbyStart = CreateTrigger()

    TriggerRegisterEnterRectSimple(gameLobbyStart, gg_rct_NextRoom)
    TriggerAddAction(gameLobbyStart, ShowStartDialog)
end

function ShowStartDialog()
    if (GetOwningPlayer(GetTriggerUnit()) == mainPlayer) then

        local dialog = DialogCreate()
        DialogSetMessage(dialog, "Начать новый этаж?")
        local yes = DialogAddButton(dialog, "Да", 0)
        local no = DialogAddButton(dialog, "Нет", 0)

        DialogDisplay(mainPlayer, dialog, true)

        local yesTrigger = CreateTrigger()
        TriggerRegisterDialogButtonEvent(yesTrigger, yes)

        TriggerAddAction(yesTrigger, StartLevel)

    end
end

function StartLevel()
    GameStart()
end