---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ofeerist.
--- DateTime: 18.02.2023 17:55
---

function AngleBetweenXY(xa, ya, xb, yb)
    return math.atan(yb - ya, xb - xa)
end