---
--- Generated by Luanalysis
--- Created by ofeerist.
--- DateTime: 18.02.2023 1:14
---
---
gridScale = 1000
semiGridScale = gridScale / 2
calibration = 300

gridWidth = 0
gridHeight = 0

function CreateMaze(width, height)
    grid = createMaze(1, 1, width, height, false)

    gridWidth = width
    gridHeight = height

    for x = 1, width do
        for y = 1, height do

            -- Main Walls

            if (grid[x][y].bottom_wall) then
                CreateWall(x * gridScale, y * gridScale - semiGridScale, 0)
                CreateWall(x * gridScale, y * gridScale, 0)
                CreateWall(x * gridScale, y * gridScale - gridScale, 0)
            else
                CreateGate(x * gridScale, y * gridScale - semiGridScale, 0)
                --CreateBocchiTheRock(x * gridScale, y * gridScale - semiGridScale - calibration, 90)
                --CreateBocchiTheRock(x * gridScale, y * gridScale - semiGridScale + calibration, 90)
            end
            if (grid[x][y].right_wall) then
                CreateWall(x * gridScale - semiGridScale, y * gridScale, 90)
                CreateWall(x * gridScale, y * gridScale, 90)
                CreateWall(x * gridScale - gridScale, y * gridScale, 90)
            else
                CreateGate(x * gridScale - semiGridScale, y * gridScale, 90)
                --CreateBocchiTheRock(x * gridScale - semiGridScale - calibration, y * gridScale, 90)
                --CreateBocchiTheRock(x * gridScale - semiGridScale + calibration, y * gridScale, 90)
            end
            if x == 1 then
                CreateWall(x * gridScale - gridScale, y * gridScale - semiGridScale, 0)
                CreateWall(x * gridScale - gridScale, y * gridScale, 0)
                CreateWall(x * gridScale - gridScale, y * gridScale - gridScale, 0)
            end
            if y == 1 then
                CreateWall(x * gridScale - semiGridScale, y * gridScale - gridScale, 90)
                CreateWall(x * gridScale, y * gridScale - gridScale, 90)
                CreateWall(x * gridScale - gridScale, y * gridScale - gridScale, 90)
            end
        end
    end

    RoomFill(grid)
end

function CreateWall(x, y, face)
    table.insert(objectsCreated,
        CreateDestructable( FourCC('LTbr'), x - semiWidth, y - semiWidth, face, 1, 0))
end
function CreateGate(x, y, face)
    table.insert(objectsCreated,
            CreateDestructable( FourCC('YTcx'), x - semiWidth, y - semiWidth, face, 1, 0))
end
function CreateBocchiTheRock(x, y, face)
    table.insert(objectsCreated,
            CreateDestructable( FourCC('LTbx'), x - semiWidth, y - semiWidth, face, 1, 0))
end
function CreateCorner(x, y, face)
    table.insert(objectsCreated,
            CreateDestructable( FourCC('LTbs'), x - semiWidth, y - semiWidth, face, 1, 0))
end