---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ofeerist.
--- DateTime: 18.02.2023 23:01
---

function MovePlayerToStart(player)
    if (playerUnits[GetPlayerId(player)] == nil) then return end

    SetUnitPositionLoc(playerUnits[GetPlayerId(player)], GetRandomLocInRect(gg_rct_PlayerStart))
    SetCameraPositionForPlayer(player, GetUnitX(playerUnits[GetPlayerId(player)]), GetUnitY(playerUnits[GetPlayerId(player)]))
    SelectUnitAddForPlayer(playerUnits[GetPlayerId(player)], player)
end