---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ofeerist.
--- DateTime: 19.02.2023 15:43
---
function PlayerDeathStart()
    local trigger = CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(trigger, EVENT_PLAYER_UNIT_DEATH)
    TriggerAddAction(trigger, function()
        for i = 0, #playerUnits do
            if (GetTriggerUnit() == playerUnits[i]) then
                local player = GetOwningPlayer(GetTriggerUnit())
                CreateNextUnit(player, currentEvolution[GetPlayerId(player)])
                MovePlayerToStart(player)

                DisplayMessageToAll(GetPlayerName(player) .. " погиб в подземелье...", 10)
            end
        end
    end)
end

function DisplayMessageToAll(text, duration)
    for i = 0, 10 do
        DisplayTimedTextToPlayer(Player(i), 0, 0, duration, text)
    end
end