---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ofeerist.
--- DateTime: 18.02.2023 19:19
---
---
playerUnits = {}
playerChooses = {}
playerChoosed = 0
function CreatePlayer(p)
    local dialog = DialogCreate()
    local alliance = DialogAddButton(dialog, "Люди", 0)
    --local orc = DialogAddButton(dialog, "Орки", 0)

    DialogDisplay(Player(p), dialog, true)

    local allianceButton = CreateTrigger()
    TriggerRegisterDialogButtonEvent(allianceButton, alliance)

    --local orcButton = CreateTrigger()
    --TriggerRegisterDialogButtonEvent(orcButton, orc)

    TriggerAddAction(allianceButton, AllianceChoose)
    --TriggerAddAction(orcButton, OrcChoose)
end

function AllianceChoose()
    local id = GetPlayerId(GetTriggerPlayer())
    playerChooses[id] = "1"

    playerChoosed = playerChoosed + 1

    playerUnits[GetPlayerId(GetTriggerPlayer())] = CreateUnit(GetTriggerPlayer(), FourCC('hpea'), 0, 0, 0)
    currentEvolution[GetPlayerId(GetTriggerPlayer())] = 'hpea'

    MovePlayerToStart(GetTriggerPlayer())
end

function OrcChoose()
    local id = GetPlayerId(GetTriggerPlayer())
    playerChooses[id] = "2"

    playerChoosed = playerChoosed + 1

    playerUnits[GetPlayerId(GetTriggerPlayer())] = CreateUnit(GetTriggerPlayer(), FourCC('opeo'), 0, 0, 0)
    currentEvolution[GetPlayerId(GetTriggerPlayer())] = 'opeo'

    MovePlayerToStart(GetTriggerPlayer())
end

function GameStart()
    CreateMaze(database[currentLevel].gridSize , database[currentLevel].gridSize)
    PlaySound("Sound/Interface/CreepAggroWhat1.flac")
end