---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ofeerist.
--- DateTime: 18.02.2023 17:30
---
pi = 3.14
function GetRandomRealOutsideCircleInSquare(centerX, centerY, width, radius)
    rx = -width + 2*width*GetRandomReal(0, 1);

    if (rx<-radius or rx>radius)  then
        ry = -width + 2*width*GetRandomReal(0, 1);
    else
        rand_inst = GetRandomReal(0, 1);
        if(rand_inst<0.5)  then
            ry = -width + 2*(width-math.sqrt(radius^2-rx^2))*rand_inst;
        else
            ry = (math.sqrt(radius^2-rx^2) - (width-math.sqrt(radius^2-rx^2)) ) + 2*(width-math.sqrt(radius^2-rx^2))*rand_inst;
        end
    end

    return {x = centerX + rx, y = centerY + ry}
end