---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ofeerist.
--- DateTime: 18.02.2023 13:20
---

triggersCreated = {}

function RoomFill(grid)
    for x = 1, gridWidth do
        for y = 1, gridHeight do
            center = {x = x * gridScale - semiGridScale, y = y * gridScale - semiGridScale}

            if (x == gridWidth and y == gridHeight) then
                CreateExit(center)

                goto continue
            end

            if (x == 1 and y == 1) then

                for p = 0, GetPlayers() do
                    SetUnitPosition(playerUnits[p], center.x  - semiWidth, center.y  - semiWidth)
                    SetCameraPositionForPlayer(Player(p), GetUnitX(playerUnits[p]), GetUnitY(playerUnits[p]))
                end

                goto continue
            end

            room = GetRandomInt(0, 10)

            -- Treasure Room
            if (room >= 0 and room <= 3) then
                rnd = GetRandomInt(0, 1)
                if (rnd == 0) then
                    CreateLowTreasureRoom(center)
                end
                if (rnd == 1) then
                    CreateMediumTreasureRoom(center)
                end
            end

            -- Unique Event Room
            if (room > 3 and room < 5) then
                rnd = GetRandomInt(0, 1)
                if (rnd == 0) then
                    CreateWell(center)
                end
                if (rnd == 1) then
                    CreatePig(center)
                end
            end

            -- Enemy Room

            if (room >= 5) then

                rnd = GetRandomInt(0, 1)

                if (rnd == 0) then
                    CreateBanditRoom(center)
                end
                if (rnd == 1) then
                    CreateAltar(center)
                end

            end

            ::continue::
        end
    end
end

function CreateFiller(raw, x, y, face, variation, scale)
    if (scale == nil) then scale = 1 end

    local dest = CreateDestructable( FourCC(raw), x - semiWidth, y - semiWidth, face, scale, variation)

    table.insert(objectsCreated, dest)
    TriggerRegisterDeathEvent(dropTrigger, dest)
end

function CreateWell(center)
    CreateFiller('B00A', center.x, center.y, 0, 1)
    local trigger = CreateTrigger()
    TriggerRegisterEnterRectSimple(trigger, Rect(center.x - semiGridScale / 2 - semiWidth, center.y - semiGridScale / 2 - semiWidth,
            center.x + semiGridScale / 2 - semiWidth, center.y + semiGridScale / 2 - semiWidth))
    TriggerAddAction(trigger, function()
        SetUnitState(GetTriggerUnit(), UNIT_STATE_LIFE, BlzGetUnitMaxHP(GetTriggerUnit()))
        DestroyTrigger(trigger)
    end)

    table.insert(triggersCreated, trigger)
end

function CreatePig(center)
    CreateFiller('B00B', center.x, center.y, 0, 1)
    local trigger = CreateTrigger()
    TriggerRegisterEnterRectSimple(trigger, Rect(center.x - semiGridScale / 2 - semiWidth, center.y - semiGridScale / 2 - semiWidth,
            center.x + semiGridScale / 2 - semiWidth, center.y + semiGridScale / 2 - semiWidth))
    TriggerAddAction(trigger, function()
        SetUnitState(GetTriggerUnit(), UNIT_STATE_LIFE, BlzGetUnitMaxHP(GetTriggerUnit()))
        SetUnitState(GetTriggerUnit(), UNIT_STATE_MANA, BlzGetUnitMaxMana(GetTriggerUnit()))
        DestroyTrigger(trigger)
    end)

    table.insert(triggersCreated, trigger)
end

function CreateAltar(center)
    size = GetRandomInt(5, 10)

    for i = 1, size do

        position =
        GetRandomRealOutsideCircleInSquare(center.x, center.y, semiGridScale - 128, semiGridScale / 2.5)

        CreateFiller('B00C',
                position.x,
                position.y,
                GetRandomReal(0, 360), GetRandomInt(0, 2))
    end

    CreateFiller('B00D', center.x, center.y, 0, 1)
    local trigger = CreateTrigger()
    TriggerRegisterEnterRectSimple(trigger, Rect(center.x - semiGridScale / 2 - semiWidth, center.y - semiGridScale / 2 - semiWidth,
            center.x + semiGridScale / 2 - semiWidth, center.y + semiGridScale / 2 - semiWidth))
    TriggerAddAction(trigger, function()
        SetUnitState(GetTriggerUnit(), UNIT_STATE_LIFE, BlzGetUnitMaxHP(GetTriggerUnit()))
        SetUnitState(GetTriggerUnit(), UNIT_STATE_MANA, BlzGetUnitMaxMana(GetTriggerUnit()))

        groupNum = GetRandomInt(1, #database[currentLevel].altar)
        for i = 1, #database[currentLevel].altar[groupNum] do
            size = GetRandomInt(database[currentLevel].altar[groupNum][i].min, database[currentLevel].altar[groupNum][i].max)
            for j = 1, size do
                local pos = {x = GetRandomReal(center.x - semiGridScale, center.x + semiGridScale),
                             y = GetRandomReal(center.y - semiGridScale, center.y + semiGridScale)}
                table.insert(unitCreated,
                        CreateUnit(Player(11), FourCC(database[currentLevel].bandits[groupNum][i].id), pos.x  - semiWidth, pos.y  - semiWidth, 0))
            end
        end

        DestroyTrigger(trigger)
    end)

    table.insert(triggersCreated, trigger)
end

function CreateLowTreasureRoom(center)
    size = GetRandomInt(5, 10)

    for i = 1, size do

        position =
        GetRandomRealOutsideCircleInSquare(center.x, center.y, semiGridScale - 128, semiGridScale / 2.5)

        CreateFiller('LTcr',
                position.x,
                position.y,
                GetRandomReal(0, 360), GetRandomInt(0, 2))
    end

    size = GetRandomInt(1, 2)

    for i = 1, size do

        position =
        GetRandomRealOutsideCircleInSquare(center.x, center.y, semiGridScale - 128, semiGridScale / 2.5)

        CreateFiller('B002', position.x, position.y, GetRandomReal(0, 360),
                GetRandomInt(0, 2), 1)
    end

    size = GetRandomInt(2, 5)

    for i = 1, size do

        position =
        GetRandomRealOutsideCircleInSquare(center.x, center.y, semiGridScale - 128, semiGridScale / 2.5)

        CreateFiller('B005', position.x, position.y, GetRandomReal(0, 360),
                1, 1)
    end

    rnd = GetRandomInt(0, 5)
    if (rnd == 0) then
        CreateFiller('B009', center.x, center.y, GetRandomReal(0, 360),
                1, GetRandomReal(1, 1))
    end
    if (rnd == 1) then
        CreateFiller('B008', center.x, center.y, GetRandomReal(0, 360),
                1, GetRandomReal(1, 1))
    end
    if (rnd > 1) then
        CreateFiller('B004', center.x, center.y, GetRandomReal(0, 360),
                1, GetRandomReal(1.5, 2))
    end

end

function CreateMediumTreasureRoom(center)
    size = GetRandomInt(2, 5)

    for i = 1, size do

        position =
        GetRandomRealOutsideCircleInSquare(center.x, center.y, semiGridScale - 128, semiGridScale / 2.5)

        CreateFiller('B003',
                position.x,
                position.y,
                GetRandomReal(0, 360), GetRandomInt(0, 2))
    end

    size = GetRandomInt(5, 10)

    for i = 1, size do

        position =
        GetRandomRealOutsideCircleInSquare(center.x, center.y, semiGridScale - 128, semiGridScale / 2.5)

        CreateFiller('B000', position.x, position.y, GetRandomReal(0, 360),
                GetRandomInt(0, 5), 1.5)
    end

    -- chest

    rnd = GetRandomInt(0, 5)
    if (rnd == 0) then
        CreateFiller('B006', center.x, center.y, GetRandomReal(0, 360),
                1, GetRandomReal(1, 1))
    end
    if (rnd == 1) then
        CreateFiller('B007', center.x, center.y, GetRandomReal(0, 360),
                1, GetRandomReal(1, 1))
    end
    if (rnd > 1) then
        CreateFiller('B001', center.x, center.y, GetRandomReal(0, 360),
                1, GetRandomReal(1.5, 2))
    end

end

function CreateBanditRoom(center)
    size = GetRandomInt(5, 20)

    for i = 1, size do
        position =
            GetRandomRealOutsideCircleInSquare(center.x, center.y, semiGridScale, semiGridScale / 2)

        angle = AngleBetweenXY(position.x, position.y, center.x, center.y) / bj_DEGTORAD

        table.insert(unitCreated,
                CreateUnit(Player(11), FourCC('hhou'), position.x  - semiWidth, position.y  - semiWidth, angle))
    end

    size = GetRandomInt(0, 3)

    for i = 1, size do
        position =
            GetRandomRealOutsideCircleInSquare(center.x, center.y, semiGridScale, semiGridScale / 2)

        angle = AngleBetweenXY(position.x, position.y, center.x, center.y) / bj_DEGTORAD

        CreateFiller('LOcg',
                position.x, position.y, angle, GetRandomInt(0, 2))
    end

    groupNum = GetRandomInt(1, #database[currentLevel].bandits)
    for i = 1, #database[currentLevel].bandits[groupNum] do
        size = GetRandomInt(database[currentLevel].bandits[groupNum][i].min, database[currentLevel].bandits[groupNum][i].max)
        for j = 1, size do
            local pos = {x = GetRandomReal(center.x - semiGridScale, center.x + semiGridScale),
                         y = GetRandomReal(center.y - semiGridScale, center.y + semiGridScale)}
            table.insert(unitCreated,
                    CreateUnit(Player(11), FourCC(database[currentLevel].bandits[groupNum][i].id), pos.x  - semiWidth, pos.y  - semiWidth, 0))
        end
    end
end