---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ofeerist.
--- DateTime: 18.02.2023 21:23
---
objectsCreated = {}
unitCreated = {}

function ShowEndDialog()
    if (not (GetOwningPlayer(GetTriggerUnit()) == mainPlayer)) then return end
    
    local dialog = DialogCreate()
    DialogSetMessage(dialog, "Закончить этаж?")
    local yes = DialogAddButton(dialog, "Да", 0)
    local no = DialogAddButton(dialog, "Нет", 0)

    DialogDisplay(mainPlayer, dialog, true)

    local yesTrigger = CreateTrigger()
    TriggerRegisterDialogButtonEvent(yesTrigger, yes)

    TriggerAddAction(yesTrigger, EndLevel)
end

function EndLevel()

    DropOnKillDestroy()

    for i = 1, #objectsCreated do
        RemoveDestructable(objectsCreated[i])
    end
    for i = 1, #unitCreated do
        RemoveUnit(unitCreated[i])
    end
    for i = 1, #itemsCreated do
        if (not IsItemOwned(itemsCreated[i])) then
            RemoveItem(itemsCreated[i])
        end
    end
    for i = 1, #triggersCreated do
        --if (not triggersCreated[i] == nil) then
            DestroyTrigger(triggersCreated[i])
        --end
    end


    DropOnKillStart()

    for i = 0, GetPlayers() do
        if (i > 4) then break end

        MovePlayerToStart(Player(i))
        NextEvolution(Player(i))
    end

    for i = 0, 3 do
        SetPlayerState(Player(i), PLAYER_STATE_RESOURCE_GOLD, GetPlayerState(Player(i), PLAYER_STATE_RESOURCE_GOLD) + database[currentLevel].gold)
        SetPlayerState(Player(i), PLAYER_STATE_RESOURCE_LUMBER, GetPlayerState(Player(i), PLAYER_STATE_RESOURCE_LUMBER) + database[currentLevel].wood)
    end

    currentLevel = currentLevel + 1

    if (currentLevel >= #database) then
        WinTimer()
    end

    PlaySound("UI/Feedback/CheckpointPopup/QuestCheckpoint.flac")
end