---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ofeerist.
--- DateTime: 18.02.2023 0:23
---
do
    local InitGlobalsOrigin = InitGlobals
    semiWidth = 0

    mainPlayer = nil
    currentLevel = 1

    players = 0

    function InitGlobals()
        InitGlobalsOrigin()
        TimerStart(CreateTimer(), .01, false, function()
            DestroyTimer(GetExpiredTimer())

            semiWidth = GetRectWidthBJ(GetWorldBounds()) / 4

            for i = 0, GetPlayers() do
                if (IsPlayerSlotState(Player(i), PLAYER_SLOT_STATE_PLAYING)) then
                    mainPlayer = Player(i)
                    break
                end
            end

            for i = 0, GetPlayers() do
                if (IsPlayerSlotState(Player(i), PLAYER_SLOT_STATE_PLAYING)) then
                    players = players + 1
                end
            end

            for i = 0, GetPlayers() do
                CreatePlayer(i)
            end

            players = players - 1

            LobbyStart()
            DropOnKillStart()
            PlayerDeathStart()
            DungeonTimerStart()

            SetPlayerState(Player(11), PLAYER_STATE_GOLD_GATHERED, 9999999)

            PlaySound("Sound/Interface/GameFound.flac")
        end)
    end
end